# -*- coding: utf-8 -*-
"""01_analisis_teks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrY2uendZEvUuFhIDD4j8HUJjjYkh-1I

# Program 1
"""

teks = input("Masukkan teks: ")

jumlah_kalimat = teks.count(".")

teks_tanpa_titik = teks.replace(".", "")

kata = teks_tanpa_titik.split()

jumlah_kata = len(kata)

print(f"Jumlah kata = {jumlah_kata}")
print(f"Jumlah kalimat = {jumlah_kalimat}")