# -*- coding: utf-8 -*-
"""01_analisis_teks

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y2F9qAISwzyD8HLZ69SL45utBo6ABwgI
"""

teks = input("Masukkan teks: ")

# Hitung jumlah kalimat
jumlah_kalimat = teks.count(".")

# Hilangkan titik agar tidak ikut dihitung sebagai bagian kata
teks_tanpa_titik = teks.replace(".", "")

# Hitung jumlah kata
jumlah_kata = len(teks_tanpa_titik.split())

print(f"Teks tersebut memuat {jumlah_kalimat} kalimat dan {jumlah_kata} kata.")