# -*- coding: utf-8 -*-
"""02_string_kalimat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BMKh07k9QBGy2j2fdM6gP8OaZik0Tncz
"""

# Program Membuat Objek String K1-K4 Sesuai Soal
K1 = "Saya tak 'kan menyerah."
K2 = 'Ia berkata, "Aku menyayangimu."'
K3 = "\"Coba jelaskan pengertian 'cross-validation' dalam Machine Learning!\""
K4 = "Surat keputusan itu bernomor 62/UN.34/19/2023."

print(K1)
print(K2)
print(K3)
print(K4)