# -*- coding: utf-8 -*-
"""05_cluster_3d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ed_XVtnRN__NA68yfxcrOgzEgX_U1cRN
"""

import math

# 1. Mendefinisikan Fungsi
def hitung_jarak(titik1, titik2):
    # Rumus jarak Euclidean 3D
    jarak = math.sqrt((titik1[0] - titik2[0])**2 +
                      (titik1[1] - titik2[1])**2 +
                      (titik1[2] - titik2[2])**2)
    return jarak

# 2. Konstanta titik pusat cluster berupa tuple
A = (2, 1, 3)
B = (1, -4, 6)
C = (-2, 3, -2)

print("--- Klasifikasi Cluster 3 Dimensi ---")

# MASUKKAN CONTOH INPUT
x = 2
y = -3
z = 6
print(f"Koordinat Titik U yang Diuji -> x: {x}, y: {y}, z: {z}")

# Menyimpan titik U sebagai tuple dengan 3 elemen (Syarat Wajib Soal)
U = (x, y, z)

# 3. Memanggil fungsi untuk masing-masing cluster
jarak_A = hitung_jarak(U, A)
jarak_B = hitung_jarak(U, B)
jarak_C = hitung_jarak(U, C)

# 4. Percabangan menentukan jarak terdekat
if jarak_A < jarak_B and jarak_A < jarak_C:
    cluster = "Cluster A"
elif jarak_B < jarak_A and jarak_B < jarak_C:
    cluster = "Cluster B"
elif jarak_C < jarak_A and jarak_C < jarak_B:
    cluster = "Cluster C"
else:
    cluster = "Jarak Sama (Tidak Dominan)"

# Menampilkan hasil (dengan pembulatan 3 angka di belakang koma agar rapi)
print(f"\nJarak titik U ke Pusat A : {jarak_A:.3f}")
print(f"Jarak titik U ke Pusat B : {jarak_B:.3f}")
print(f"Jarak titik U ke Pusat C : {jarak_C:.3f}")
print(f">> Titik U digolongkan sebagai anggota: {cluster}")
