# -*- coding: utf-8 -*-
"""praktikum4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KxmYWbJlXctiteebiV4Py9PSiykF46kp
"""

#Integer>angka
#Float>desimal
#string>text
#Boolean>true false

angka=18

print(angka)

print(type(angka))

angka1=3.14

print(type(angka1))

text1="Statistika"
print(type(text1))

logical=10>5
print(logical)

print(type(logical))

#List, itu kurung siku "[]"
angka=[1,2,3,4]
print(angka)

buah=["apel","jeruk","mangga"]
print(buah)

data=[1,"apel",3.14,True]
print(data)

buah[0] #0 di pyton pertama

buah.append("semangka")
print(buah)

buah.remove("apel")
print(buah)



#Tuple #Tdk bisa diubah seperti list dan pakai kurung biasa "()"
data=(1,2,3)
print(data)

campuran=(1,"apel",3.14,True)
print(campuran)

a=(5,)
b=(5)

(1,2,3)
(1,"apel",3.14,True)
print(type(a))

print(type(buah))

print(type(campuran))

campuran=list(campuran)
campuran.remove("apel")

print(campuran)

campuran[0]=10
print(campuran)

campuran=tuple(campuran)

data_mahasiswa={
    "nama":"Andi",
    "umur":20,
    "nilai":85
}
print(data_mahasiswa)

data_mahasiswa2={
    "mahasiswa1":{"nama":"Andi","umur":20,"nilai":85},
    "mahasiswa2":{"nama":"Budi","umur":21,"nilai":90}
    }
print(data_mahasiswa2)

print(data_mahasiswa['nama'])
print(data_mahasiswa2['mahasiswa1']["nilai"])

!pip install rumpy

!pip install numpy

import numpy as np

#Array 1 dimensi
arry = np.array([1,2,3,4])
print(arry)
#Matriks
Matriks=np.array([ [1,2,3], [4,5,6]
])
print(Matriks)

arr=np.array([
[1,2,3], [4,5,6] ])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

print(arr.mean())
print(arr.max())
print(arr.min())
print(arr.sum())
print(arr+2)
print(arr*2)
print(arr/2)

#baris ke-1
print(tabel_mahasiswa.iloc[0])

#kolom ke-1
print(tabel_mahasiswa.iloc[:,0])
print(tabel_mahasiswa["nama"])

#baris ke-2, kolom ke-3
print(tabel_mahasiswa.iloc[1,2])
print(tabel_mahasiswa.iloc[1]["nilai"])

import pandas as pd

tabel_mahasiswa=pd.DataFrame({
    "nama":["Andi","Budi","Caca"],
    "umur":[20,21,22],
    "nilai":[85,90,95]
})
print(tabel_mahasiswa)

list(range(1,11))

list(range(1,11,2))

list(range(5))



!pip install pandas

import pandas as pd

tabel_mahasiswa=pd.DataFrame({
    "nama":["Andi","Budi","Caca"],
    "umur":[20,21,22],
    "nilai":[85,90,95]
})
print(tabel_mahasiswa)

print(tabel_mahasiswa.info())

print(tabel_mahasiswa.head())

["A","B"]*3

[x for x in ["A","B"] for _ in  range(2)]

import numpy as np
np.repeat(["A","B"],2)









































