# -*- coding: utf-8 -*-
"""Project Alpro Program 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rO_sZRyRS-AxyjQQ8C7wJu5Z5hlDqSkc
"""

import math

def hitung_akar_kuadrat():
    print("=== Program Pencari Akar Persamaan Kuadrat ===")
    print("Bentuk umum: ax^2 + bx + c = 0")

    try:
        # Membaca koefisien-koefisien persamaan kuadrat dari pengguna
        a = float(input("Masukkan koefisien a: "))
        b = float(input("Masukkan koefisien b: "))
        c = float(input("Masukkan koefisien c: "))

        # Validasi dasar: a tidak boleh 0 untuk persamaan kuadrat
        if a == 0:
            print("Nilai 'a' tidak boleh 0. Ini bukan persamaan kuadrat.")
            return

        # Menghitung nilai diskriminan
        diskriminan = b**2 - 4 * a * c

        # Menentukan dan mencetak jenis akar
        if diskriminan > 0:
            x1 = (-b + math.sqrt(diskriminan)) / (2 * a)
            x2 = (-b - math.sqrt(diskriminan)) / (2 * a)
            print("\nPersamaan memiliki dua akar real yang berbeda:")
            # Mengatur tampilan agar akar bilangan real ditampilkan dalam tiga desimal
            print(f"x1 = {x1:.3f}")
            print(f"x2 = {x2:.3f}")

        elif diskriminan == 0:
            x = -b / (2 * a)
            print("\nPersamaan memiliki satu akar real (akar kembar):")
            # Mengatur tampilan agar akar bilangan real ditampilkan dalam tiga desimal
            print(f"x = {x:.3f}")

        else:
            # Jika diskriminan < 0, maka akar bertipe imajiner
            print("\nPersamaan tersebut hanya memiliki akar-akar imajiner.")

    except ValueError:
        # Menangani kondisi khusus jika pengguna tidak memasukkan angka
        print("\nInput tidak valid! Harap masukkan nilai berupa angka.")

# Menjalankan program
if __name__ == "__main__":
    hitung_akar_kuadrat()
